export default {
  TODO_ADD: 'TODO_ADD',
  TODO_ADD_SUCCESS: 'TODO_ADD_SUCCESS',
  
  TODO_TOGGLE: 'TODO_TOGGLE',
  TODO_FILTER: 'TODO_FILTER',
  
  SHOW_ALL: 'ALL',
  SHOW_COMPLETED: 'COMPLETED',
  SHOW_INCOMPLETE: 'INCOMPLETE',

  TODO_GET_START: 'TODO_GET_START',
  TODO_GET: 'TODO_GET',
  TODO_GET_SUCCESS: 'TODO_GET_SUCCESS',

  TODO_CLEAR: 'TODO_CLEAR',
}