export default {
  TODO_GET_START: 'TODO_GET_START',
  TODO_GET: 'TODO_GET',
  TODO_GET_SUCCESS: 'TODO_GET_SUCCESS',

  TODO_ADD_START: 'TODO_ADD_START',
  TODO_ADD: 'TODO_ADD',
  TODO_ADD_SUCCESS: 'TODO_ADD_SUCCESS',
  
  SHOW_ALL: '',
  SHOW_COMPLETED: 1,
  SHOW_INCOMPLETE: 0,

  TODO_FILTER_START: 'TODO_FILTER_START',
  TODO_FILTER: 'TODO_FILTER',
  TODO_FILTER_SUCCESS: 'TODO_FILTER_SUCCESS',

  TODO_TOGGLE_START: 'TODO_TOGGLE_START',
  TODO_TOGGLE: 'TODO_TOGGLE',
  TODO_TOGGLE_SUCCESS: 'TODO_TOGGLE_SUCCESS',

  TODO_CLEAR_START: 'TODO_CLEAR_START',
  TODO_CLEAR: 'TODO_CLEAR',
  TODO_CLEAR_SUCCESS: 'TODO_CLEAR_SUCCESS',
}